
#添加考试
POST http://localhost:8080/api/admin/invigilation/exams
token:ae6b9dbceef4b0428313523ad2de74397cf6a31e88414ede957d4add59be71305d758b926c1fce69b1406e01bccb983b
Content-Type: application/json

{
  "name": "test",
  "beginTime": "2019-06-06 13:00:00",
  "endTime": "2019-06-06 15:00:00",
  "location": "006",
  "numbersOfTeacher": 2
}

###
/api/admin/invigilation
GET http://localhost:8080/api/admin/exam_details/7/1

###

DELETE http://localhost:8080/api/admin/exam_details/28


